### ISSUE TITLE
[Feature Request] FictionPress Support 

### ISSUE THREAD

**Issue by jeancinq** [lesma/FanFiction-Tools#10]
Hi,
It would be nice if FanFiction-Tools also worked on https://www.fictionpress.com/ an original stories site
that has basically the same layout as the one of fanfiction.net.

The only differences I see are that there are that :
- Instead of having stories/crossovers as main categories, there is fiction/poetry
- Inside those main categories, there are sub-categories like fantasy or thriller...
- There are no fandoms (original fiction instead of fanfiction).

Thanks for your awesome work.

**Comment by lesma** [comment]
Done in v1.4.0
