### ISSUE TITLE
Upload multiple documents

### ISSUE THREAD

**Issue by mcepl** [lesma/FanFiction-Tools#13]
It would be rather interesting and quite useful if your extension was able to upload multiple documents at once. I have to upload at https://www.fanfiction.net/docs/docs.php and then even add https://www.fanfiction.net/story/story_edit_content.php?storyid=XXXX each story individually. If this addon was able to upload multiple chapters, it would be unique functionality.

**Comment by lesma** [comment]
I dont think this will be possbile via an extension
