### ISSUE TITLE
Next page doesnt load

### ISSUE THREAD

**Issue by gundamwin** [lesma/FanFiction-Tools#2]
![grafik](https://cloud.githubusercontent.com/assets/28867560/26313345/e52b7e2a-3f0a-11e7-8d73-fd2c4e9e9faf.png)

Next page doesnt load. It works with the chapters, but not with the menu page. 

Win10, Firefox 53.0.2

**Comment by gundamwin** [comment]
Next page doesnt load. It works with the chapters, but not with the menu page.

Win10, Firefox 53.0.2

**Comment by lesma** [comment]
Fix has been submitted to Mozilla for review
