### ISSUE TITLE
Page loading wrong!

### ISSUE THREAD

**Issue by mehmehmehmememeh** [lesma/FanFiction-Tools#3]
![image](https://user-images.githubusercontent.com/31095219/29405031-a63419b6-8334-11e7-9b8d-ff175846de17.png)

**Comment by mehmehmehmememeh** [comment]
get back to me at fallout.vulpine@gmail.com

**Comment by lesma** [comment]
Hi,

It is working for me currently, so likely not an issue with a change in the fanfiction site. Good in a way but does make it harder for me to diagnose your issue. Can you let me know/try the following and let me know how you get on:

1)	Does it work with the fanfiction-tools extension disabled? https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons
2)	Have  you confirmed the zoom and text size https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages ? 
3)	If you disable all other extensions does it work? If so can you work out which extension is causing you issues?
4)	If you are happy can you try refreshing firefox https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings ?
5)	What version of firefox are you using?

Thanks

Lesma

**Comment by mehmehmehmememeh** [comment]
This is only happening if the option to load all chapters at once is enebled, works fine if on another option or off. Howerver a new problem occurred it was fine but after refreshing the page the Community areas story list wouldn't work...

![image](https://user-images.githubusercontent.com/31095219/29431265-3b3929de-838f-11e7-91ab-1446a2ec50ad.png)

The listing loads like the above while the plug in is active, also this was fine until a little ago (few hours), then went wrong when page was reloaded.

This is my version I'm on auto update for stable versions.
https://www.mozilla.org/en-US/firefox/55.0/releasenotes/

I've always had zoom at 150% and had no troubles till now. Been using you plug in for about a month going on two. These are the first troubles I've had.

I've been using the same plug ins in that time which are below.

![image](https://user-images.githubusercontent.com/31095219/29431527-25169032-8390-11e7-9903-b7f8c202f80d.png)

 Thanks for the reply!

**Comment by mehmehmehmememeh** [comment]
It's also not the chapter count, which was a total of 50 with the defect at around chapter 26/7... I've read longer works with more chapter no problems...

**Comment by mehmehmehmememeh** [comment]
I did restart firefox between community areas working and failing...

**Comment by mehmehmehmememeh** [comment]
correction 33 to 34 are the chapters.

**Comment by mehmehmehmememeh** [comment]
Disabled all other plug ins no change.

**Comment by mehmehmehmememeh** [comment]
will restart firefox bbs

**Comment by mehmehmehmememeh** [comment]
Firefox installed an update but no change.

**Comment by mehmehmehmememeh** [comment]
the story no loading right is easy to handle by swapping to sing chapter autoload, just annoying as my net can be spotty and having it all loaded saves me from getting stuck at a chapter's end.
However, the community area not loading right is more urgent as I've to disable the plug in for it to load right

**Comment by mehmehmehmememeh** [comment]
If possible devote more time to the second problem (community) than the first (story). Thank you!

**Comment by mehmehmehmememeh** [comment]
The first can be easily worked around by disbling/ removing the bottom area or changing the colour code for the bottom of the page to completely transparent.

**Comment by mehmehmehmememeh** [comment]
where as the community page loads somewhat but after a half second goes blank like in the image, which is when the plug states it's loaded the page.

**Comment by mehmehmehmememeh** [comment]
even with autoload lists off same problem without plug in message

**Comment by lesma** [comment]
I expect both problems are due to the same underlying cause, but are still having trouble replicating your issue. Is possible that FF are in the process of rolling out an update which will break it, and just has not reached my area yet.

Does it happen on all communities as soon as you go into one e.g. https://www.fanfiction.net/community/Alternate-First-Contact-War/88942/ ?

Did you try to see if you encounter similar issues with the Fanfiction tools plugin disabled?

**Comment by mehmehmehmememeh** [comment]
I've tried two other communities one larger one smaller, same problem. no problems at all with fanfiction tools disabled, I'd had it disabled until I noticed your reply.

**Comment by mehmehmehmememeh** [comment]
Just noted this happens as well.
![image](https://user-images.githubusercontent.com/31095219/29432808-e1682fe4-8394-11e7-88e4-bb8445132d0b.png)

**Comment by mehmehmehmememeh** [comment]
Same problem if filter view set to default

**Comment by mehmehmehmememeh** [comment]
It's also not that the lists don't load it's that they disappear.

**Comment by mehmehmehmememeh** [comment]
Is there a way to keep my settings if i reinstall the plug in?

**Comment by mehmehmehmememeh** [comment]
Also checked another story in another lower zoom, same problem between 20 and 21 of a 33 chapter 300,000+ word work.

![image](https://user-images.githubusercontent.com/31095219/29433317-94ee9962-8396-11e7-9b14-c26aa52d76f5.png)

Again, only happens when at load all chapters.

**Comment by lesma** [comment]
Hi,

Still haven't been able to reproduce your issue yet, is it still happening for you?

if it is can you let me know

1) The exact version of firefox (are you now on 55.0.2)?
2) What are your options in the extension (should be dine with just the ones from the main page)?
3) The resolution of your monitor (from your screen shot I would guess 1920 x 1080)?

Thanks

**Comment by mehmehmehmememeh** [comment]
am updated to 55.0.2 
![image](https://user-images.githubusercontent.com/31095219/29498219-35e7ed32-85ef-11e7-8aae-33286cdb3651.png)
![image](https://user-images.githubusercontent.com/31095219/29498220-3e2d9af0-85ef-11e7-9bfe-cc1333bd11d7.png)
![image](https://user-images.githubusercontent.com/31095219/29498223-4aabf010-85ef-11e7-8ac3-1f3d71c33c2e.png)
![image](https://user-images.githubusercontent.com/31095219/29498228-5b0a6b76-85ef-11e7-89d1-52797b57732f.png)
![image](https://user-images.githubusercontent.com/31095219/29498237-79989bc6-85ef-11e7-83dc-5e9ff9f276ca.png)

**Comment by mehmehmehmememeh** [comment]
resolution is 1920x1080

**Comment by lesma** [comment]
For the issues with the community's, can you confirm the precise text you have, from your screen shot it looks like you may have a space before english (was able to replicate your issue by doing this), if this is the case it will look for the language " english" which none of them are.

For the other issue, can you expand more on what the effect is and how to trigger it?
1) Does the white box appear after load or in the middle of reading?
2) Does the white box stay visible while looking
3) Does it always occur on every story or only some?

**Comment by mehmehmehmememeh** [comment]
I've found it only happens when a sufficient number of chapters are loaded... the word count also influences it to some degree with a low word count having no problem or completely fine but high count fewer chapters needed.
white box is permanently visible and occurs when theres too much loaded, not 100% sure it will spawn on low word counts

**Comment by mehmehmehmememeh** [comment]
while that is important I can get round it by setting it to single chapter auto load and refreshing the page every few chapters.
however with the story lists not loading, i have more of a problem as the lack of filtering means i take longer to find a suitable read... longer by hours :(

**Comment by mehmehmehmememeh** [comment]
well as ive said they load but disapear less than a second later

**Comment by lesma** [comment]
The story list issue you report is what I received when specifying " english" as the language, it appears that the story language / black listed words can allow improper values. Can you try clearing them and see if you still get the issue?

**Comment by mehmehmehmememeh** [comment]
with both the story language and the black list blank problem solved...

**Comment by mehmehmehmememeh** [comment]
here's my blacklist,
m/preg | yaoi | crack | sasunaru | hiatus | sexual assault | rape | noncon | dubcon | incomplete | inuyasha | narusasu | m/m | hpdm | dmhp | male x male | boyxboy | 
can you see the problem?

**Comment by mehmehmehmememeh** [comment]
m/preg | yaoi | hiatus | rape | noncon | dubcon | incomplete | m/m | male x male | boyxboy | boy x boy | 
This works...
fault was probably due to too many factors that it failed... but you're the programmer (more knowledgeable person) here

**Comment by mehmehmehmememeh** [comment]
thanks for the assistance so far!
hope a solution to the page not loading correctly in stories is discovered, but thank you in advance to that as well

**Comment by mehmehmehmememeh** [comment]
wait nope, just made it take longer the lists still disappear

**Comment by mehmehmehmememeh** [comment]
m/preg|yaoi|hiatus|rape|noncon|dubcon|incomplete|m/m|male x male|boyxboy|boy x boy|
this definitely works, it's the spaces! maybe...

**Comment by mehmehmehmememeh** [comment]
I was using spaces before and after the pipes to make it more legible but it backfired... please advise others of this. "xxx | yyy" breaks it/ this won't "xxx|yyy"

**Comment by mehmehmehmememeh** [comment]
While somewhat unrelated i just came up with a question, what of character filtering, plans of implementation or not possible... ?

**Comment by mehmehmehmememeh** [comment]
oh, your coloured word count seems to change according to average words per chapter not overall word count... was this intentional?

**Comment by mehmehmehmememeh** [comment]
![image](https://user-images.githubusercontent.com/31095219/29500250-e285b3c2-8616-11e7-8c0d-f2deb0638269.png)
![image](https://user-images.githubusercontent.com/31095219/29500254-f23f21ae-8616-11e7-97f2-f8bb4b61a539.png)
![image](https://user-images.githubusercontent.com/31095219/29500259-05830ed8-8617-11e7-81b2-0c256eeaa618.png)

**Comment by lesma** [comment]
Hi,
yes it is intentional to be word counts per chapter.

Have raised an enhancement to look into providing some form of validation regarding spaces #4

Have manged to reproduce your other issue, their is a limit of the size that the content can be. Should be able to override this, have raised a separate issue for this #5

For character filters how would you see that working and how would it be better than the current FF.net implementation?

**Comment by lesma** [comment]
Looking into the issue with spaces in black lists etc, it does not seem to be an issue with having spaces in between the pipes but it is an issue having one at the tnd. e.g. "aaa | bbb |" is fine but "aaa | bbb | " is not.

**Comment by mehmehmehmememeh** [comment]
Thank you.

**Comment by lesma** [comment]
New version of the add on had  just been published as v1.3.0 which hopefully you will revive soon which will solve the issue with long stories. Also changes a couple of other things: https://github.com/lesma/FanFiction-Tools/releases/tag/v1.3.0

**Comment by mehmehmehmememeh** [comment]
I'd like to be able to prevent more characters, at the moment it only allows 2 to be selected as un wanted but with fanfiction works like mass effect and harry potter theres a much larger amount of love interests than are preventable, before moving to firefox I was on chrome, there was a plug in for that I much like and it allowed allowed a drop down of the character list with a tick or cross depending if you wanted them to be in the works shown.

![image](https://user-images.githubusercontent.com/31095219/29616211-aa5e7b70-8808-11e7-815f-c8619719ef89.png)

https://chrome.google.com/webstore/detail/fanfic-filter/cfoadfegpeknjcnocdlfdfjkonfimhfj

**Comment by mehmehmehmememeh** [comment]
![image](https://user-images.githubusercontent.com/31095219/29616333-0889d37a-8809-11e7-9df3-82d212e43bb0.png)

![image](https://user-images.githubusercontent.com/31095219/29616380-3008913e-8809-11e7-82e4-55a746f49d5b.png)

**Comment by mehmehmehmememeh** [comment]
As to a previous point is it possible to have a toggle switch as to wether the word count looks at overall or chapter?
I'd like to make note that these aren't demands or anything, and I'm not paying you so you dan't have to do anything, these are mainly my personal preferences and suggestions.
Thank you.

**Comment by mehmehmehmememeh** [comment]
I really love how your plug in, if the page reloads, goes to the most recent chapter loaded, really a time saver, and one I've not seen elsewhere.

**Comment by lesma** [comment]
Great glad you like it, TBH I did not write most of it, just took over as it was not being maintained.

Since the last release tou should be able to now switch between colouring by chapter or story length or not at all via a drop down on the world colour tab.

That filtering does look very good, will see if I can contact the author. Do see that they had a version for firefox, but does not work with the current version.

**Comment by lesma** [comment]
Sorry for the delay, still just scraped in under a year!

Decided the easiest way was to just port the fanfic-filter into a Firefox web extension add on, which is now available at: https://addons.mozilla.org/en-GB/firefox/addon/fanfic-filter-quantum/ git hub for this is in https://github.com/lesma/FanFic-Filter.

In the latest version of Fanfiction-tools (released yesterday) I added an option to indicate you are also using fanfic filter which disables conflicting functionality in fanfiction tools.
