### ISSUE TITLE
It'd be nice if 'autoload full story' and disabled 'Hide chapters drop-down list' worked together

### ISSUE THREAD

**Issue by i30817** [lesma/FanFiction-Tools#9]
Currently the dropdown box in these circumstances tries to load 'chapter X' selected, which then triggers the autoload of the fullstory so nothing happens.

Except the comment textbox gets posted to the right chapter when you review, i suppose that is good and would be nice to preserve.

**Comment by lesma** [comment]
Thanks for the report, will try and work on this at some point, expect it may not be that simple a fix but fingers crossed

**Comment by lesma** [comment]
Done in v1.4.0
